# Generated by Django 5.2.8 on 2025-12-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('type', models.PositiveIntegerField()),
                ('taste', models.PositiveIntegerField()),
                ('servings', models.PositiveIntegerField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
