# Generated by Django 5.2.8 on 2025-12-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='servings',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='meal',
            name='taste',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(max_length=2),
        ),
    ]
